# Generated by Django 5.0.1 on 2026-02-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='agent1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='team',
            name='agent2',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
