# Generated by Django 5.0.1 on 2026-02-08 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_team_agent1_team_agent2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='agent1',
        ),
        migrations.RemoveField(
            model_name='team',
            name='agent2',
        ),
    ]
